
export const profileData = {
  "intro": {
    "name": "Dr. Santosh K. Sahu",
    "title": "Professor",
    "department": "Discipline of Mechanical Engineering",
    "institution": "Indian Institute of Technology Indore",
    "address": "Indore - 453552, Madhya Pradesh, India",
    "email": "sksahu@iiti.ac.in",
    "bio": [
      "Dr. Sahu is a Professor of the Department of Mechanical Engineering at Indian Institute of Technology (IIT) Indore. He received his BE and MTech all in Mechanical Engineering from University College of Engineering Burla (currently VSSUT) and Indian Institute of Technology Bombay, respectively. He received his PhD from Indian Institute of Technology Kharagpur in 2009 and joined IIT Indore in October 2009 as an Assistant Professor; since then he has been serving at Department of Mechanical Engineering, currently as a Professor. He has been a visiting scholar and visiting researcher at Purdue University, USA during 2011 and 2019, respectively. Prior to this, he served as an Assistant Professor in the Department of Mechanical Engineering at National Institute of Technology (NIT) Rourkela.",
      "Dr. Sahu’s research group is actively engaged in the development of cutting edge research to cater the cooling needs of next generation high performance thermal systems. His research group works on various areas including rewetting of hot surfaces, quenching of hot stationary and moving surfaces, heat transfer enhancement with nanofluids, heat transfer behavior of gaseous flows in micro devices, pool boiling heat transfer, impinging jets, synthetic jets, heat exchanging equipment, phase change materials and thermal management of electronics.",
      "Dr. Sahu has published over 170 articles including 81 in international journals, 7 book chapters and one patent. He has supervised 10 PhD students, 3 masters students, one post-doctoral fellow and supervising 6 PhD students.",
      "Dr. Sahu has received the prestigious IUSSTF Research Fellowship by Indo-US Science and Technology Forum for Engineering Sciences in 2011. He has served technical programme committee of numerous conferences and is a reviewer of various international journals. He is life member of the ISHMT and member of the ASME."
    ],
    "recentEvents": [
      {
        "title": "A short course on Fuel Cell Technology and its Engineering Aspects",
        "link": "docs/FLYER-Course.pdf",
        "btnText": "Details"
      }
    ]
  },
  "research_interests": [
    "Thermal Engineering",
    "Thermal-hydraulics of nuclear reactors",
    "Nanofluids",
    "Gas flow through micro channels",
    "Impinging jets",
    "Synthetic jets",
    "Heat exchangers",
    "Pool boiling heat transfer",
    "Phase change materials",
    "Thermal management of electronics"
  ],
  "education": [
    "PhD, Mechanical Engineering, Indian Institute of Technology Kharagpur, India.",
    "MTech, Mechanical Engineering (Thermal and Fluids Engineering), Indian Institute of Technology Bombay, India.",
    "BE, Mechanical Engineering, University College of Engineering (presently VSSUT) Burla, India."
  ],
  "experience": [
    "Professor (February 2022- continuing), Department of Mechanical Engineering, Indian Institute of Technology Indore, India.",
    "Associate Professor (June 2016-February 2022), Department of Mechanical Engineering, Indian Institute of Technology Indore, India.",
    "Visiting Researcher (October 2-19, 2019), School of Nuclear Engineering, Purdue University, USA.",
    "Visiting Scholar, (September 2011-January 2012), School of Nuclear Engineering, Purdue University, USA",
    "Assistant Professor, (October 2009-June 2016), Discipline of Mechanical Engineering, Indian Institute of Technology Indore, India.",
    "Assistant Professor, (March 2008-October 2009), National Institute of Technology Rourkela, India."
  ],
  "awards": [
    "IUSSTF (Indo-US Science & Technology Forum) Fellow, 2011",
    "Research article selected as qualified student award winner of the student paper competition in the 24<sup>th</sup> International Conference on Nuclear Engineering (ICONE24), Charlotte, NC, USA, 2016.",
    "Research article selected as qualified student award winner of the student paper competition in the 25<sup>th</sup> International Conference on Nuclear Engineering (ICONE25), Shanghai, China, 2017.",
    "Research article selected as qualified student award winner of the student paper competition in the 26<sup>th</sup> International Conference on Nuclear Engineering (ICONE26), London, UK, 2018.",
    "DST Inspire fellowship is awarded to PhD student to carry out doctoral research at IIT Indore, 2018",
    "Research article selected as qualified student award winner of the student paper competition in the 26<sup>th</sup> International Conference on ASME 2019 power conference(POWER2019) Utah, USA,2019",
    "Research article selected as qualified student award winner of the student paper competition for 28<sup>th</sup> Conference on Nuclear Engineering Joint with the ASME 2020 Power Conference (ICONE28-POWER2020-6524), California, USA, 2020.",
    "Research article selected as Best Presentation Award in Asia region in 28<sup>th</sup> Conference on Nuclear Engineering Joint with the ASME 2020 Power Conference (ICONE28-POWER2020-6524), California, USA, 2020.",
    "SERB-Purdue University Overseas Visiting Doctoral Fellowship (OVDF) is awarded to PhD student to carry out doctoral research at Purdue University, USA during January 2019- January 2020.",
    "Prime Minister's Research Fellowship (PMRF) is awarded to PhD students to carry out doctoral research at IIT Indore (2020, 2021).",
    "Young Scientist Award is provided to PhD student at 37<sup>th</sup> Madhya Pradesh Young Scientist Congress, 2022."
  ],
  "invited_articles": [
    "Invitation to contribute an article for Thermal Science, Institute of nuclear Sciences, Vinca, Serbia, 2009",
    "Invitation to contribute an article on the special issue for Comptes Rendus Mecanique (Elsevier, London), 2012",
    "Invitation to contribute an article on the special issue for Heat Transfer Engineering (Taylor and Francis), 2015",
    "Invitation to contribute an article on the special issue for ASME Journal of Heat transfer, 2016"
  ],
  "courses": [
    "ME 203 Fluid Mechanics",
    "ME 204 Fluid Machinery",
    "ME154 Workshop Practice",
    "ME 254 Fluid Mechanics and Machinery Lab",
    "IC 211 Experimental Engineering Lab",
    "ME 258 Manufacturing Processes Lab",
    "Short term course on Measurement Techniques in Thermal Engineering: Recent Advances, IIT Indore, May 30-31, 2014."
  ],
  "internship": [
    "We have vacancies for motivated PG/UG candidates to join the Fluid Mechanics and Machinery Lab at IIT Indore for working on long-term research projects (Minimum internship period is 3 months)."
  ],
  "projects": [
    "Development of novel shape stabilized and flame redundant phase change composite for thermal management of battery modules, Industry sponsored project, (PI, consultancy project, Status: Ongoing)",
    "A novel thermal management system for electric vehicle batteries using phase change composite, CSIR, India (PI, Status: Ongoing).",
    "Unraveling the potential of graphene quantum dots for hydrogen storage in fuel cells, DST, India (Co-PI, Status: Ongoing).",
    "Development of light weight heat sink integrated with phase change material (PCM) for cooling applications, DST, India (PI, Status: Completed)",
    "Quenching of hot Stationery/Moving hot surface, Council of Scientific Research Investigation, (CSIR), India, (PI, Status: Completed)",
    "Numerical investigation of flow and heat transfer characteristics of three dimensional impinging jet/jets on an isothermal hot surface, (SERB NPDFship of Dr. P. M. Prabhu; My role: Mentor) SERB, Department of Science and Technology, India (Status: Completed)"
  ],
  "patents": [
    "Avadhesh Kumar Sharma, Mayank Modak, Akash Kumar Jain, Santosh K. Sahu, Design and development of stationary/moving surfaces for impingement jet cooling (Indian patent application No: 201721017344, Published on: July 07, 2017)"
  ],
  "activities": [
    "Editorial Board Member, ISRN Mechanical Engineering, Hindawai Publication, USA (2014-2019)",
    "Member, American Society of Mechanical Engineering (ASME); Life Member, Indian Society for Heat and Mass transfer (ISHMT)",
    "Reviewer of International Journals: International Journal of Heat and Mass Transfer (Elsevier), International communication in Heat Transfer (Elsevier),Nuclear Engineering and Design (Elsevier), International Journal of Thermal Science (Elsevier), Applied Thermal Engineering (Elsevier), Ocean Engineering (Elsevier), Resource-Efficient Technologies (Elsevier), Journal of Wind Engineering & Industrial Aerodynamics (Elsevier), Journal of King Saud University (Science) (Elsevier), Comptes Rendus Mecanique (Elsevier), Heat and Mass Transfer (Springer), Sadhana-Academy Proceedings in Engineering Science (Springer), Experimental Heat Transfer (Taylor and Francis), International Journal of Green Energy (Taylor and Francis), International Journal of Ambient Energy (Taylor and Francis), Chemical Engineering Communications (Taylor and Francis), Heat Transfer Engineering (Taylor and Francis), Thermal Science (International Scientific Journal), Defense Science Journal, Journal of Renewable and Sustainable Energy (American Institute of Physics)"
  ],
  "students": {
    "PhD - Ongoing": [
      "Vivek Saxena",
      "Pradeep Kumar Singh",
      "Pawan Sharma",
      "Akhalesh Sharma",
      "Jay Kumar Joshi",
      "Nitin Luhadiya"
    ],
    "MS - Ongoing": [
      "Pradunmya Dutta"
    ],
    "Post Doctoral (completed)": [
      "Dr. P. Maheandera Prabu, SERB National Post-Doctoral Fellow (September 2017-September 2019)"
    ],
    "PhD (submitted/completed)": [
      "Pushpanjay Kumar Singh, 2022, (Thesis Title: Heat Transfer Characteristics of Hot Surface by Synthetic Jet Impingement), thesis submitted.",
      "Anuj Kumar, 2021, (Thesis Title: Phase Change Material Based Heat Sink for Thermal Management of Electronic Devices), current Position: Post-Doctoral Fellow, Indian Institute of Technology, Mumbai.",
      "Rohit Kothari, 2021, (Thesis Title: Phase Change Materials for Thermal Management and Thermal Energy Storage Applications), Current Position: Post-Doctoral Fellow, Department of Mechanical Engineering, Technical University of Denmark, Denmark.",
      "Vishal Nirgude, 2020 (Thesis Title: Pool Boiling Heat Transfer Characteristics of Structured Surfaces), Current position: Post-Doctoral Fellow, Department of Advanced Nuclear Engineering, Seoul National University, Republic of Korea",
      "Saurabh Yadav, 2020 (Thesis Title: Heat transfer and fluid flow characteristics of double pipe heat exchanger with passive techniques) Current position: Post-Doctoral Fellow, School of Mechanical Engineering, Yeungnam University, Republic of Korea.",
      "Avadhesh Kumar Sharma, 2020 (Thesis Title: Thermal and rewetting behaviour of hot stationary and moving surfaces) Current position: Post-Doctoral Fellow, Graduate School of Engineering, The University of Tokyo, Japan.",
      "Mayank Modak, 2018, (Thesis Title: Heat Transfer behavior of hot surface by impinging jet), Current position: Post-Doctrol Fellow, Department of Advanced Nuclear Engineering, Seoul National University, Republic of Korea.",
      "Hari Mohan, 2016, (Thesis Title: Heat transfer characteristics of gaseous flows through micro channels).",
      "Sandesh Kumar Chougule, 2015, (Thesis Title: Enhancement in heat transfer with nanofluids), Current position: Assistant Professor, The LNM Institute of Information Technology, Jaipur, India.",
      "Manish Kumar Agrawal, 2014, (Thesis Title: Rewetting of hot surfaces), Current position: Assistant Professor, Mahindra Ecole Centrale, Hyderabad."
    ],
    "MS-Research/MTech(Completed)": [
      "Jayant Sutradhar, 2021 (Thesis Title: Thermal performance analysis of phase change material based systems with volumetric expansion and shrinkage)",
      "Pritinika Behera, 2009 (Thesis Title: Analysis of transient heat conduction in different geometries)",
      "Chandranan Kumar, 2009 (Thesis Title: Counter current flow phenomena and pressure drop calculations in annular geometry)"
    ],
    "BTech Projects (Completed)": [
      "Kapilan Baskar, Samanth Kumar and Saran Sreyes, Augmentation of heat transfer performance in an automobile radiator using nanofluid, 2013",
      "Satish Chandra and Palash Gupta, Effect of nozzle inclination on heat transfer during liquid jet impingement, 2013",
      "Krati Garg and Srikananth Srinivasan, Analysis of heat transfer by impinging jets, 2014.",
      "Hemang Kumar Desai, Modeling gust response of unmanned aerial vehicle, (With Prof. Murali Damodaran, Professor, IIT Gandhinagar), 2014",
      "Rahul Agrawal, Molecular dynamics studies on ethanol-water osmotic flow at nanoscale, (With Prof. Gautam Biswas, Professor, IIT Guwahati and Prof. Dipankar Bandopadhyaya, IIT Guwahati), 2014",
      "Poris Bharvath Raj, Study of pool boiling, 2015.",
      "Parantak Sharma and Ashutosh K. Yadav, Heat transfer characteristics of down ward facing hot horizontal surfaces using mist jet impingement, 2016.",
      "Deshraj Meena and Nitin Goyal, Study of front propagation of phase change materials, 2017.",
      "Anirudh Soni and Monika Meena, Cooling of hot surfaces by mist jet impingement, 2017.",
      "Vaidya Dattaraj Vilas and Vinay Shelke, Thermal management of electronic components using nano-enhanced phase change material (NePCM), 2018.",
      "Shailesh Kumar and Ashish Kishor, Heat transfer characteristics of hot surface by synthetic jet impingement, 2018.",
      "Pawan kumar Singh, Rushikesh Vaidya, Thermal performance enhancement of PCM based cross finned heat sink for electronic cooling, 2019.",
      "Anjali Parashar, Design, Control and Hydrodynamic Analysis for a Thruster-based Underwater Vehicle, (With Dr. Santhakumar Mohan, Associate Professor IIT Palakkad), 2019.",
      "Akash Kumar Singh and Ameya Atul Chitre, The performance analysis of phase change material based heat sinks with hollow fins, 2020",
      "Ayush Kumar Shah and Shubhendu Narayan Tripathi, Experimental and numerical investigation of synthetic jet impingement cooling, 2020",
      "Arpit sahu, Govind Agrawal, Heat transfer characteristics of impinging jet on curved and protruded surfaces, 2022",
      "Aastha Luthra, Thermal performance of fin finned heat sinks by using Nano enhanced phase change material, 2022",
      "Harshit Zinwal & Gaurav Nagar, Phase Change composite based cross finned heat sinks for thermal management of electronic devices, 2022"
    ]
  },
  "publications": {
    "Book Chapters": [
      "Kumar A., Kothari R., Singh P. K., Paulraj M. P., Sahu S. K., Kundalwal S. I., Numerical simulation of PCM based heat sink with plate fins for thermal management of electronic components, In: F. Cavas-Martinez, F. Chaari, F. Gherardini, M. Haddar, V. Ivanov, Y.W. Kwon, J. Trojanowska (Eds.), Lecture Notes in Mechanical Engineering (Springer) https://doi.org/10.1007/978-981-33-4165-4_20.",
      "Kothari R., Das S., Sahu S. K., Kundalwal S. I., Approximate Analytical Model for Solidification Process in a Rectangular Phase-Change Material Storage with Internal Fins, In: Suneet Singh and Venkatasailanathan Ramadesigan (Eds.), Advances in Energy Research, Vol. 1. Springer Proceedings in Energy. Springer, Singapore, 2020, https://doi.org/10.1007/978-981-15-2666-4_22.",
      "Sharma A. K., Modak M., Sahu S. K , Agrawal M. K., Infrared Thermal Imaging Technique for Temperature Measurement in Various Thermal Systems, In: A. Mukhopadhyay, S. Sen, D. N. Basu, S. Mondal (Eds.), Dynamics and Control of Energy Systems, Springer, 2019.",
      "Agrawal M. K., Sahu S. K., Application of Variational Integral Method to analyze variety of rewetting problems, In: Jordan Hristov and Rachid Bennacer (Eds.), Heat Conduction: Methods, Applications and Research, Nova Science Publishers, Inc., USA, 2018.",
      "Agrawal M. K., Modak M., Sahu S. K., Heat transfer characteristics of hot surface using high alcohol surfcant by impinging liquid jet, In: A. K. Saha , D. Das, R. Srivastava, P. K. Panigrahi, K. Muralidhar (Eds.), Fluid Mechanics and Fluid Power-Contemporary Research, Springer, 2016.",
      "Agrawal M. K., Modak M., Chandra S., Gupta P., Sahu S. K., An experimental investigation to analyze the heat transfer characteristics of hot surface by obliquely impinging liquid jet, In: A. K. Saha , D. Das, R. Srivastava, P. K. Panigrahi, K. Muralidhar (Eds.), Fluid Mechanics and Fluid Power-Contemporary Research, Springer, 2016.",
      "Kushwaha H. M., Sahu S. K., Analysis of heat transfer in the slip flow region between parallel plates, In: A. K. Saha , D. Das, R. Srivastava, P. K. Panigrahi, K. Muralidhar (Eds.), Fluid Mechanics and Fluid Power-Contemporary Research, Springer, 2016."
    ],
    "International Journals": [
      "Sharma P., Sahu S. K., Yadav H., Experimental investigation of flow and thermal characteristics of synthetic jet issuing from sharp-edged orifice, Exp. Heat Transf (In Press).",
      "Singh P. K., Shah A. K., Tripathi S. N.,Yadav H., Prabhat K. Upadhyay, Santosh K. Sahu, Numerical Investigation of the Flow and Thermal Behavior of Impinging Single and Multi-orifice Synthetic Jets with Different Waveforms, Numerical Heat Transfer, Part A: Applications (In Press).",
      "Sharma A., Kothari R., Sahu S. K., 2022, Effect of fin location on constrained melting heat transfer of phase change material in a spherical capsule: A numerical study, Journal of Energy Storage (In Press)",
      "Saxena V., Kothari R., Kumar A., Sahu S. K., Kundalwal S. I., A theoretical model for effective thermal conductivity of open-cell-coated metal foams saturated with fluid/phase change material, https://doi.org/10.1002/er.8190.",
      "Kumar A., Kothari R., Saxena V., Sahu S. K., Kundalwal S. I., Experimental investigation on paraffin wax-based heat sinks with cross plate fin arrangement for cooling of electronic components, Journal of Thermal Analysis and Calorimetry (2022), https://doi.org/10.1007/s10973-022-11223-9.",
      "Modak M., Sahu S. K. , Park H. S. , 2022, Generalized semi-mechanistic model of impinging jet quenching heat transfer, International Journal of Heat and Mass Transfer, 192, 122896",
      "Das A. K., Sahu S. K., Panda A. K., 2022, Current status and prospects of alternate liquid transportation fuels in compression ignition engines: A critical review, Renewable and Sustainable Energy Reviews, 161, 112358",
      "Singh P. K., Renganathan M., Yadav H. K., Sahu S. K., Upadhyay P. K, Agrawal Amit, 2022, An Experimental Investigation of the Flow-field and Thermal Characteristics of Synthetic Jet Impingement with Different Waveforms, International Journal of Heat and Mass Transfer (In Press)",
      "Jayanta Sutradhar, Rohit Kothari, S K Sahu, 2021, Melting and solidification analysis of phase change material-metal foam composite with expansion/shrinkage void in rectangular system, Journal of Energy Storage, DOI: https://doi.org/10.1016/j.est.2021.103596",
      "Nitin Luhadiya, Kundalwal SI, Sahu SK, 2022, Adsorption and desorption behavior of titanium-decorated polycrystalline graphene towards hydrogen storage: A molecular dynamics study, Applied Physics A, 128, 4,2022.",
      "Jay Joshi and S K Sahu, 2021, Heat transfer characteristics of flat and concave surfaces by circular and elliptical jet impingement, Experimental Heat Transfer, DOI: https://doi.org/10.1080/08916152.2021.1995082",
      "Singh P. K., Sahu, S. K., Upadhyay P. K, 2021, Experimental and Numerical Investigation of the Thermal Performance of Impinging Synthetic Jets with Different Waveforms, Experimental Heat Transfer, DOI: https://doi.org/10.1080/08916152.2021.1984341",
      "A. Kumar, R. Kothari, S. K. Sahu, and S. I. Kundalwal, 2021, A comparative study and optimization of phase change material based heat sinks for thermal management of electronic components, Journal of Energy Storage, https://doi.org/10.1016/j.est.2021.103224",
      "Pawan Sharma, Singh P. K., Sahu, S. K., H K Yadav, 2021,A critical Review on Flow and Heat Transfer Characteristics of Synthetic Jet, INAE Letters, DOI: https://doi.org/10.1007/s41403-021-00264-5",
      "Jayanta Sutradhar, Rohit Kothari, S K Sahu, 2021, Solidification and melting model of phase change material with volumetric shrinkage/expansion void in an annulus, Applied Thermal Engineering, DOI: https://doi.org/10.1016/j.applthermaleng.2021.117202",
      "Anuj Kumar, Rohit Kothari, SK Sahu, SI Kundalwal, 2021, Thermal performance of heat sink using nano-enhanced phase change material (NePCM) for cooling of electronic components, Microelectronic Reliability, 121, 114144, DOI: https://doi.org/10.1016/j.microrel.2021.114144",
      "Modak M., Sahu S. K., Park H. S., 2021, An experimental study on heat transfer of different aqueous surfactant solutions horizontal impinging jet using infrared thermography, Applied Thermal Engineering, 188, 116668, DOI: https://doi.org/10.1016/j.applthermaleng.2021.116668",
      "R. Kothari, S. K. Sahu, S. I. Kundalwal, and S. Sahoo, 2021, Experimental investigation of the effect of inclination angle on the performance of phase change material based finned heat sink, Journal of Energy Storage, 37, 102462, DOI: https://doi.org/10.1016/j.est.2021.102462",
      "Kumar A., Kothari R., Sahu S. K., Kundalwal S. I., Paulraj M. P., 2021, Numerical simulation of cross plate fin heat sink filled with PCM for cooling application of portable electronic devices, International Journal of Energy Research, DOI: https://doi.org/10.1002/er.6404",
      "Kothari R., Sahu S. K., Kundalwal S. I., 2021, Investigation on thermal characteristics of nano enhanced phase change material based finned and unfinned heat sinks for thermal management system,Chemical Engineering Processing and Process Intensification, 162,108328, DOI: https://doi.org/10.1016/j.cep.2021.108328",
      "Nitin Luhadiya, Kundalwal SI, Sahu SK, 2021, Investigation of hydrogen adsorption behaviour of graphene under varied conditions using a novel energy-centered method, Carbon Letters, 31(8):1-12, DOI: https://doi.org/10.1007/s42823-021-00236-3",
      "Kothari R., Sahu S. K., Kundalwal S. I., Mahalkar P., 2020, Thermal performance of phase change material–based heat sink for passive cooling of electronic components: An experimental study, International Journal of Energy Research, DOI: https://doi.org/10.1002/er.6215",
      "Kumar A., Kothari R., Sahu S. K., Kundalwal S. I., 2020, Selection of phase-change material for thermal management of electronic devices using multi-attribute decision making technique, International Journal of Energy Research, DOI: https://doi.org/10.1002/er.5896",
      "Singh P. K., Sahu S. K., Upadhyay P. K., 2020, Experimental investigation of the thermal behaviour of a single cavity and multiple-orifice synthetic jet impingement driven by electromagnetic actuator for electronics cooling, Experimental Heat Transfer, DOI: https://doi.org/10.1080/08916152.2020.1825546",
      "Singh P. K. , Sahu, S. K., Upadhyay P. K., Jain A. K., 2020, Experimental investigation on thermal characteristics of hot surface by synthetic jet impingement, Applied Thermal Engineering, 165: 114596.",
      "Nirgude, V. V., Sahu, S. K., 2020, Heat transfer enhancement in nucleate pool boiling using laser processed surfaces: Effect of laser wavelength and power variation, Thermochimica Acta, 694:178788.",
      "Nirgude, V. V., Sahu, S. K., 2020, Nucleate boiling heat transfer performance of different laser processed copper surfaces, International Journal of Green Energy, 17 (1):38-47.",
      "Nirgude, V. V., Sahu, S. K., 2020, Nucleate boiling heat transfer performance of laser textured copper surfaces, Journal of Enhanced Heat Transfer, 26(6):597-618.",
      "Yadav S., Paulraj M. P., Sahu S. K., 2020, Thermal performance of air to water heat exchanger with plain surface disc turbulators: Experimental and Numerical study, Heat and Mass Transfer, 56:1777-1791.",
      "Yadav S., Sahu S. K., 2020, Effect of helical surface disc turbulator on thermal and friction characteristics of double pipe water to air heat exchanger, Experimental Heat Transfer. DOI: https://doi.org/10.1080/08916152.2020.1714819",
      "Sharma A. K., Sahu S. K., 2019, The thermal and rewetting behavior of hot moving surface by water jet impingement, Applied Thermal Engineering, 159, 113950.",
      "Sharma A. K., Lodhi U K, Kumar G., Sahu S.K., 2019, Effect of Jet inclination and Coolant Flow Rate on Thermal and Rewetting Behavior during Bottom Jet Impingement on Hot Horizontal Surface, Steel Research International, 90(10), 1900171.",
      "Paulraj M. P., Sahu S. K., 2019, Conjugate heat transfer enhancement of laminar slot jets with various nanofluids on an array of protruding hot sources using MPM approach, Numerical Heat Transfer, Part A: Applications, 76:4, 232-253.",
      "Yadav S., Sahu S. K., 2019, Effect of helical surface disc turbulators on heat transfer and friction factor characteristics in the annuli of double pipe heat exchanger: An experimental study, Chemical Engineering and Technology, 42(6), 1205–1213.",
      "Sharma A. K., Sahu S. K., 2019, An experimental study on heat transfer and rewetting behvaiour of hot horizontal downward facing hot surface by mist jet impingement, Applied Thermal Engineering, 151, 459-474.",
      "Yadav S., Sahu S. K., 2019, Heat transfer and friction factor characteristics of annuli formed by the smooth inner tube and corrugated outer tube – An experimental study, Experimental Heat Transfer, 23, 18-39.",
      "Kothari R., Das S., Sahu S. K., Kundalwal S.I., 2019, Analysis of solidification in a finite PCM storage with internal fins by employing Heat Balance Integral method, International Journal of Energy Research. 43(12), 6366-6388.",
      "Yadav S., Sahu S. K., 2018, Heat transfer augmentation in double pipe water to air counter flow heat exchanger with helical surface disc turbulators, Chemical Engineering and Processing: Process Intensification, 135, 120-132.",
      "Nirgude V. V., Sahu, S. K., 2018, Enhancement in nucleate pool boiling heat transfer on nanosecond laser processed copper surfaces, Experimental Heat Transfer.DOI :https://doi.org/10.1080/08916152.2018.1559262",
      "Kothari R., Sahu S. K., Kundalwal S. I., 2018, Comprehensive analysis of melting and solidification of a phase change material in an annulus, Heat and Mass Transfer.DOI :https://doi.org/10.1007/s00231-018-2453-9",
      "Sharma A. K., Modak M., Sahu S. K., 2018, The heat transfer characteristics and rewetting behvaiour of hot horizontal downward facing surface by round water jet impingement, Applied Thermal Engineering, 138, 603-617.",
      "Kothari R., Sahu S. K., Kundalwal S. I., 2018, Transversely isotropic thermal properties of carbon nanotubes containing vacancies, Acta Mechanica, 229 (7), 2787-2800.",
      "Modak M., Chougule S. S., Sahu S. K., 2018, Experimental Investigation on Heat Transfer Characteristics of Hot Surface by Using CuO-water Nanofluids in Circular Jet Impingement Cooling, ASME Journal of Heat Transfer, 140, 1–10.",
      "Modak M., Sharma A. K., Sahu S. K., 2018, An Experimental Investigation on Heat Transfer Enhancement in Circular Jet Impingement on Hot Surfaces by using Al2O3/water Nano-Fuids and Aqueous High-alcohol Surfactant Solution, Experimental Heat Transfer, 31, 275-296.",
      "Chougule S. S., Nirgude V. V., Shewale S. P., Pise A. T., Sahu S. K., Shah, H., 2018, Application of Paraffin Based Nanocomposite in Heat Pipe Module for Electronic Equipment Cooling, Materials Today: Proceedings, 5 (11) Part 2, 23333-23338.",
      "Nirgude V. V., Sahu S. K., 2017, Enhancement of nucleate boiling heat transfer using structured surfaces, Chemical Engineering & Processing: Process Intensification,122, 222-234.",
      "Kothari R., Kundalwal S. I., Sahu S. K., Ray M. C., 2017, Modeling of thermo mechanical Properties of Polymeric Hybrid Nanocomposites, Polymer Composites, DOI:10.1002/pc.24483",
      "Chougule S. S., Nirgude V. V., Sahu S. K., 2017, Experimental Study on Laminar Forced Convection of Al2O3/Water and Multiwall Carbon Nanotubes/Water Nanofluid of Varied Particle Concentration with Helical Twisted Tape Inserts in Pipe Flow, Heat Transfer Engineering, DOI: 10.1080/01457632.2017.1341235",
      "Modak M., Srinivasan S., Garg K., Chougule S. S., Agarwal M. K., Sahu S. K., 2017,Theoretical and experimental study on heat transfer characteristics of normally impinging two dimensional jets on a hot surface, International Journal of Thermal Sciences, 112, 174-187.",
      "Kushwaha H. M., Sahu S. K.,2017, Comprehensive analysis of convective heat transfer in parallel plate microchannel with viscous dissipation and constant heat flux boundary conditions, Journal of The Institution of Engineers (India): Series C, 98 (5), 553-566.",
      "Chougule S. S., Nirgude V. V., Gharge P. D., Modak M., Sahu S. K., 2016, Heat transfer enhancement of low volume concentration CNT/water nanofluid and wire coil inserts in a circular tube, Energy Procedia, 90, 552 – 558.",
      "Kushwaha H. M., Raj P. B., Sahu S. K., 2016, Effect of Shear Work on the Heat Transfer Characteristicsof Gaseous Flows in Microchannels, Chemical Engineering and Technology, 40 (1),103-115.",
      "Kushwaha H. M., Sahu S. K., 2016, Analysis of Slip Flow Heat Transfer between Two Unsymmetrically Heated Parallel Plates with Viscous Dissipation, Sadhana-Academy Proceedings in Engineering Science, 41 (6), 653-666.",
      "Modak M., Garg K., Sahu S. K., 2015, Stagnation Region Heat Transfer of Axi-symmetric Impinging Jets on Solid Surfaces, Chemical Engineering and Technology, 38, 2127-2136.",
      "Modak M., Srinivasan S., Garg K., Chougule S. S., Agarwal M. K., Sahu S. K., 2015, Experimental investigation of heat transfer characteristics of the hot surface using Al2O3-water nanofluids, Chemical Engineering and Processing: Process Intensification, 91,104-113.",
      "Agrawal M. K., Sahu S. K., 2015, Analysis of three-region conduction controlled rewetting of a hot surface by variational method, Heat Transfer Engineering, 37 (9),763-773.",
      "Agrawal M. K., Sahu S. K., 2015, An Experimental Study on the Rewetting of Hot Vertical Surface by Circular Water Jet Impingement, Experimental Heat Transfer, 29 (2),151-172.",
      "Chougule S. S., Sahu S. K., 2015, Thermal performance of nanofluids charged heat pipes with phase change material for electronics cooling, ASME Journal of Electronic Packaging, 137(2), 021004.",
      "Kushwaha H. M., Sahu S. K., 2015, The Effects of Viscous Dissipation and Rarefaction on Parallel Plates with Constant Heat Flux Boundary Conditions, Chemical Engineering & Technology, 38,235-245.",
      "Chougule S. S., Sahu S. K., 2015, Heat Transfer and Friction Characteristics of Al2O3/water and CNT/water Nanofluids in Transition flow using Helical Screw Tape Inserts-A Comparative Study, Chemical Engineering and Processing: Process Intensification, 88, 78-88.",
      "Sahu, S. K., Das, P. K., Bhattacharyya S., 2015, Analytical and semi-analytical models of conduction controlled rewetting: a state of the art review, Thermal Science, 19 (5),1479-1496.",
      "Chougule S. S., Sahu S. K., 2014, Performance of CNT-water nanofluid charged wickless heat pipe flat plate solar collectors having different filling ratio, ASME Journal of Solar Energy Engineering, 137(2), 024501.",
      "Agrawal M. K., Sahu S. K., 2014, Analysis of Multi-Region Conduction-Controlled Rewetting of a Hot Surface Under The Influence of Precursory Cooling by Variational Integral Method, Applied Thermal Engineering, 73, 265-274.",
      "Chougule S. S., Sahu S. K., 2014, Comparative Study on Heat Transfer Enhancement of Low Volume Concentration of Al2O3-Water and CNT-Water Nanofluids in Transition Regime using Helical Screw Tape Inserts, Experimental Heat Transfer, 29 (1),17-36.",
      "Kushwaha H. M., Sahu S. K., 2014, Analysis of gaseous flow in a micropipe with second order velocity slip and temperature jump boundary conditions, Heat and Mass Transfer, 50 (12), 1649-1659.",
      "Chougule S. S., Sahu S. K., 2014, Experimental investigation of heat transfer augmentation in automobile radiator with CNT/water nanofluid, ASME Journal of Thermal Science and Engineering Applications, 6 (4), 041009",
      "Chougule S. S., Sahu S. K., 2014, Comparative study of cooling performance of automobile radiator using Al2O3/water and CNT/water nanofluid, ASME Journal of Nanotechnology in Engineering and Medicine, 5 (1),011001",
      "Chougule S. S., Sahu S. K., 2014, Comparative Study on Heat Transfer Enhancement of Low Volume Concentration of Al2O3-Water and CNT-Water Nanofluids in Laminar Regime using Helical Screw Tape Inserts, ASME Journal of Nanotechnology and Medicines, 4 (4),040904.",
      "Kushwaha H. M., Sahu S. K., 2014, Analysis of gaseous flow between parallel plates by second order velocity slip and temperature jump boundary conditions, Heat Transfer-Asian Research, 43 (8),734-748",
      "Chougule S. S., Sahu S. K. and Pise T. A., 2013, Thermal performance of two phase thermosyphon flat-plate solar collectors by using nanofluid, ASME Journal of Solar Energy Engineering, 136 (1),014503.",
      "Chougule S. S., Sahu S. K., Pise T. A., 2013, Performance enhancement of two phase thermo-syphon flat-plate solar collectors by using surfactant and nano-fluid, Frontiers in Heat Pipes (FHP),4,013002 (FHP), 4, 013002",
      "Agrawal M. K., Sahu S. K., 2013 Analysis of conduction-controlled rewetting of a hot surface by variational method, Heat and Mass Transfer 49,963-971.",
      "Sahu S. K., Behera P., 2012, An improved lumped model for transient heat conduction in different geometries, Computational Thermal Science, 4 (1), 39-48.",
      "Sahu S. K., Behera P., 2012, An improved lumped analysis for transient conduction in different geometries with heat generation, Comptes Rendus Mecanique, 340, 477–484 (Invited article).",
      "Patil N. D., Das P. K., Bhattacharyya S., Sahu S.K., 2012, An experimental assessment of cooling of a 54-rod bundle by in-bundle injection, Nuclear Engineering and Design, 250, 500-511.",
      "Sahu S. K., Das P. K., Bhattacharyya S., 2010, An experimental investigation on the quenching of a hot vertical heater by water injection at high flow rate, Nuclear Engineering and Design, 240, 1558-1568.",
      "Sahu S. K., Das P. K., Bhattacharyya S., 2009, How good is Goodman’s Heat Balance Integral Method for analyzing the rewetting of hot surfaces, Thermal Science, 13, 97-112. (Invited article).",
      "Sahu S. K., Das P. K., Bhattacharyya S., 2009, A three-region conduction controlled rewetting analysis by the Heat Balance Integral Method, International Journal of Thermal Sciences, 48, 2100-2107.",
      "Sahu S. K., Das P. K., Bhattacharyya S., 2008, Rewetting analysis of hot vertical surfaces with internal heat source by the Heat Balance Integral Method, Heat and Mass Transfer, 44, 1247-1256.",
      "Sahu S. K., Das P. K., Bhattacharyya S., 2008, Rewetting analysis of hot vertical surfaces with precursory cooling by the Heat Balance Integral Method, ASME Journal of Heat Transfer, 130, 024504-(1-5).",
      "Sahu S. K., Das P. K., Bhattacharyya S., 2006, A Comprehensive Analysis of Conduction Controlled Rewetting by the Heat Balance Integral Method, Int. Journal of Heat and Mass Transfer, 49, 4978-4986."
    ],
    "International Conferences": [
      "Singh P. K., Tripathi S. N., Shah A. K., Sahu S. K., Upadhyay P. K., Yadav H. K, 2021,Numerical investigation on the flow and thermal behaviour of synthetic jet with different waveforms, IHMTC-2021, Proceedings of the 26th National and 4rd International ISHMT-ASTFE Heat and Mass Transfer Conference, IIT Madras, Chennai, India, December 17-20, 2021.",
      "Kumar A., Singh A. K., Chitre A., Kothari R., Saxena V., Sahu S. K., Kundalwal S. I., 2021, Thermal performance of PCM based heat sink with solid and hollow fins for thermal management of electronics, Proceedings of the 26th National and 4rd International ISHMT-ASTFE Heat and Mass Transfer Conference, IIT Madras, Chennai, India, December 17-20, 2021.",
      "Joshi J., Sharma P. Sharma A., Sahu S. K, 2021, Effect of elliptical nozzle geometry on the heat transfer characteristics of a curved surface, Proceedings of the 26th National and 4rd International ISHMT-ASTFE Heat and Mass Transfer Conference, IIT Madras, Chennai, India, December 17-20, 2021.",
      "Singh P. K., Joshi J., Sahu S. K, 2021, Experimental investigation to identify the effect of thin metal foam on heat transfer characteristics of a heated plate, Proceedings of the 26th National and 4rd International ISHMT-ASTFE Heat and Mass Transfer Conference, IIT Madras, Chennai, India, December 17-20, 2021.",
      "Sharma P., Joshi J., Singh P. K., Sahu S. K., Yadav H. K, 2021, Heat transfer enhancement of an impinging synthetic air jet using sharp-edged orifice, Proceedings of the 26th National and 4rd International ISHMT-ASTFE Heat and Mass Transfer Conference, IIT Madras, Chennai, India, December 17-20, 2021.",
      "Sharma A., Kothari R., Saxena V., Sahu S. K, 2021, Effect of fin location on constrained melting heat transfer of phase change material in a spherical capsule: A numerical study, Proceedings of the 26th National and 4rd International ISHMT-ASTFE Heat and Mass Transfer Conference, IIT Madras, Chennai, India, December 17-20, 2021.",
      "Choudhary K., Lote C., Sharma P., Sahu S. K., Yadav H, 2021, Investigation of Fluid Flow and Heat transfer Characteristics of Synthetic Jet Impingement at different Strouhal Number, Proceedings of the 26th National and 4rd International ISHMT-ASTFE Heat and Mass Transfer Conference, IIT Madras, Chennai, India, December 17-20, 2021.",
      "Saxena V., Dey H., Kumar A., Sharma A., Sahu S. K., Kundalwal S. I, 2021, Numerical investigation of phase change material enhanced Li-ion battery pack using the dual potential multi-scale multi-dimensional (MSMD) approach, Proceedings of the 26th National and 4rd International ISHMT-ASTFE Heat and Mass Transfer Conference, IIT Madras, Chennai, India, December 17-20, 2021.",
      "Saxena V., Kothari R., Sahu S. K., Kundalwal S. I., 2021, An analytical approach for predicting the effective thermal conductivity of coated metal Foam infiltrated with Phase change material, Proceedings of the 26th National and 4rd International ISHMT-ASTFE Heat and Mass Transfer Conference, IIT Madras, Chennai, India, December 17-20, 2021.",
      "Sutradhar J, Kothari R, Saxena V, Sahu SK, 2021, Investigation of solidification of nonenhanced phase change material considering volumetric shrinkage: an analytical approach, Proceedings of 15th International Conference on Heat Transfer, Fluid Mechanics and thermodynamics (ATE-HEFAT), 2021",
      "Vivek Saxena, Rohit Kothari, Anuj Kumar, Santosh K. Sahu, Shailesh I. Kundalwal, 2021, Theoretical Modeling for the Effective Thermal Conductivity of Open-Cell Infiltrated Metal Foams, Proceedings of 15th International Conference on Heat Transfer, Fluid Mechanics and thermodynamics (ATE-HEFAT), 2021",
      "A Kumar, R Kothari, SK Sahu, SI Kundalwal, A Sharma, 2021, Investigation of Phase Change Material Integrated with High Thermal Conductive Carbon Foam Inside Heat Sinks for Thermal Management of Electronic Components, Proceedings of ASME 2021 Power Conference, 2021",
      "A Sharma, R Kothari, A Kumar, SK Sahu, 2021, Effect of Fin Orientation on PCM Melting in a Spherical Enclosure for Latent Heat Storage, Proceedings of ASME 2021 Power Conference, 2021",
      "Singh P. K., Shah A., Tripathi S.N., Sahu S. K., Upadhyay P.K., Experimental and numerical analysis of 2D synthetic jet with different waveforms, Proceedings of the 8th International and 47th National Conference on Fluid Mechanics and Fluid Power (FMFP-2020), IIT Guwahati, India, December 09-11, 2020.",
      "Singh P. K., Shah A., Tripathi S. N., Sahu S. K., Upadhyay P. K., A Numerical investigation on the flow and thermal behaviour of a single cavity multiple orifice synthetic jet, Proceedings of the 8th International and 47th National Conference on Fluid Mechanics and Fluid Power (FMFP-2020), IIT Guwahati, India, , December 09-11, 2020.",
      "Kumar A., Kothari R., Singh P. K., Vaidya R., Sahu S. K., Kundalwal S. I., Thermal performance enhancement of PCM based cross plate finned heat sink for electronic cooling, Proceedings of the 8th International and 47th National Conference on Fluid Mechanics and Fluid Power (FMFP-2020), IIT Guwahati, India, December 09-11, 2020.",
      "Joshi J., Singh P. K., Sahu S. K., Experimental investigation of elliptical nozzle on the concave surface with a various aspect ratio, Proceedings of the 8th International and 47th National Conference on Fluid Mechanics and Fluid Power (FMFP-2020), IIT Guwahati, India, December 09-11, 2020.",
      "Sutradhar J., Kothari R., Kumar A., Sahu S. K., Study of solidification process of PCM with shrinkage void effect in an annulus, Proceedings of the 8th International and 47th National Conference on Fluid Mechanics and Fluid Power (FMFP-2020), IIT Guwahati, India, December 09-11, 2020.",
      "Kothari R., Rvenkar S.T., Sahu S. K., Kundalwal S. I., A comparative study of constrained and unconstrained melting inside a sphere, Proceedings of the 2020 28th Conference on Nuclear Engineering Joint with the ASME 2020 Power Conference (ICONE28-POWER2020-6524), Anaheim, California, USA, August 2-6, 2020. (Winner of Qualified Student Award by ASME and Best Presentation Award in Asia Region)",
      "Singh P. K., Kothari R., Sahu S. K., Upadhyay P. K., Singh S., Experimental and numerical investigation of thermal performance of synthetic jet impingement, proceedings of the 2020 28th Conference on Nuclear Engineering joint with the ASME 2020 Power Conference (ICONE28-POWER2020-6524), Anaheim, California, USA, August 2-6, 2020.",
      "Singh P. K., Kumar A., Shah A., Kishor A., Sahu S. K., Upadhyay P. K., Singh S., Flow and heat transfer analysis of an axisymmetric impinging synthetic jet for electronic cooling, Proceedings of the International Conference on Innovations in Thermo-Fluid Engineering and Sciences [ICITFES - 2020] NIT Rourkela, India, February 10-12, 2020.",
      "Kumar A., Kothari R., Singh P. K., Paulraj M. P., Sahu S.K., Kundalwal S. I., Numerical simulation of PCM based heat sink with plate fins for thermal management of electronic components, Proceedings of the International Conference on Innovations in Thermo-Fluid Engineering and Sciences [ICITFES - 2020] NIT Rourkela, India, February 10-12, 2020.",
      "Singh P. K., Kumar S., Upadhyay P. K., Sahu S. K., Chandel S. S., Heat transfer characteristics of multiple-orifice synthetic jet impingement, Proceedings of 25th National and 3rd International ISHMT-ASTFE Heat and Mass Transfer Conference, Dec 28-31, 2019, IIT Roorkee, Roorkee, India.",
      "Kothari R., Kumar A., Sahu S. K., Kundalwal S. I., Analytical model for melting process in a rectangular phase change material storage with internal fins, Proceedings of 25thNational and 3rd International ISHMT-ASTFE Heat and Mass Transfer Conference, Dec 28-31, 2019, IIT Roorkee, Roorkee, India.",
      "Kumar A., Kothari R., Sahu S. K., Kundalwal S. I., Effect of CuO nanoparticle in PCM Integrated heat sink for thermal management of electronic component: An experimental study, Proceedings of 25thNational and 3rd International ISHMT-ASTFE Heat and Mass Transfer Conference, Dec 28-31, 2019, IIT Roorkee, Roorkee, India.",
      "Kothari R., Vaidya D.V., Shelke V., Sahu S. K., Kundalwal S. I., Experimental investigation of thermal performance of nano-enhanced phase change materials for thermal management of electronic components, ASME 2019 power conference (POWER2019-1883), Salt Lake City, Utah, USA, June 14-18, 2019. (Winner of Qualified Student Award by ASME)",
      "Paulraj M. P., Sharma A. K., Kumar A., Sahu S. K., Experimental investigation of heat transfer enhancement on impinging jet cooling using surface laser treatment, Proceedings of the 46th National Conference on Fluid Mechanics and Fluid Power (FMFP), December 9-11, 2019, PSG College of Technology, Coimbatore, India.",
      "Chandel S. S., Verma A., Paulraj M. P., Sahu S. K., Nusselt number and friction factor behaviour of circular wavy transverse ribs artificially roughened solar air heater, Ncrafs19, IOP conference series, Accepted, 2019.",
      "Yadav S., Sharma A. K., Sahu S. K., Thermal Performance in Annuli of Double Pipe Heat Exchanger Using Helical Surface Disc Turbulators. Proceedings of 7th International and 45th National Conference on Fluid Mechanics and Fluid Power (FMFP2018), Dec 10-12, 2018. IIT Bombay, Mumbai, India.",
      "Sharma A. K., Lodhi U. K., Kumar G., Yadav S., Sahu S. K., Rewetting Analysis of Downward Facing Hot Surfaces using Mist Jet. Proceedings of 7th International and 45th National Conference on Fluid Mechanics and Fluid Power (FMFP2018), Dec 10-12, 2018. IIT Bombay, Mumbai, India.",
      "Kothari R., Sahoo S. P., Sahu S. K., Kundalwal S. I., Experimental Investigation of the Effect of Inclination Angle on the Performance of Phase Change Material Based Finned Heat Sinks. Proceedings of 7th International and 45th National Conference on Fluid Mechanics and Fluid Power (FMFP2018), Dec 10-12, 2018. IIT Bombay, Mumbai, India.",
      "Singh P. K., Kothari R., Upadhyay P. K., Sahu S. K., Heat transfer characteristics of hot surface by synthetic jet impingement, Proceedings of 7thInternational and 45th National Conference on Fluid Mechanics and Fluid Power Dec 10-12, 2018. IIT Bombay, Mumbai, India.",
      "Paulraj M. P., Sahu S. K., Numerical Investigation of Three-dimensional Flow and Heat Transfer for Normally Impinging Two-dimensional Slot Jet on an Isothermal Hot Surface, Proceedings of 7thInternational and 45th National Conference on Fluid Mechanics and Fluid Power Dec 10-12, 2018, IIT Bombay, Mumbai, India.",
      "Yadav S., Paulraj M. P., Sahu S. K., Experimental investigation of heat transfer and friction factor characteristics using helical surface ring turbulators in an annuli of double pipe heat exchanger, In Proceedings of ASME 2018 Power Conference collocated with the 12th International Conference on Energy Sustainability and the ASME 2018 Nuclear Forum, 24–28 June, 2018, Florida, USA",
      "Sharma A. K., Modak M., Sahu S. K., Rewetting Analysis of Hot Moving Surface by Round Water Jet Impingement. Proceedings of the ASME 2018 26th International Conference on Nuclear Engineering (ICONE26), London, UK, July 22-26, 2018.(Selected as Qualified Student Award Winner of the student paper competition)",
      "Sharma A. K., Meena M., Soni A., Sahu S. K., Effect of Subcooling and Nozzle Diameter on Heat Transfer Characteristics of Downward Facing Hot Surfaces using Mist Jet. Proceedings of the ASME 2018 26th International Conference on Nuclear Engineering (ICONE26), London, UK, July 22-26, 2018.",
      "Kothari R., Mahalkar P., Sahu S. K., Kundalwal S. I., Experimental investigations on thermal performance of PCM based heat sink for passive cooling of electronic components, Proceedings of the ASME 2018 16th International Conference on Nanochannels, Microchannels, and Minichannels (ICNMM2018), Dubrovnik, Croatia, June 10-13, 2018.",
      "Paulraj M. P., Sahu S. K., Marimuthu U., Singh P. K., Sharma A. K., Turbulent Flow and Heat Transfer in an Impinging Jet on Protruding Hot Surface Using Nanofluids, Proceedings of 11th International Conference on Computational Heat and Mass Transfer (ICCHMT2018), Cracow, 21-24 May, 2018.",
      "Sharma A. K., Mishra S. K., Modak M., Sahu S. K., An Experimental Investigation of Rewetting of Hot Horizontal Surface by Bottom Jet Impingement, Proceedings of 24th National and 2nd International ISHMT-ASTFE Heat and Mass Transfer Conference (IHMTC2017), BITS Hyderabad, Telangana, India, Dec 27-31, 2017.",
      "Kothari R., Malviya S., Singh S. K., Sahu S. K., Kundalwal S. I., Thermal management of electric vehicle battery modules with phase change materials”, Proceedings of 24th National and 2nd International ISHMT-ASTFE Heat and Mass Transfer Conference (IHMTC2017), BITS Hyderabad, Telangana, India, Dec 27-31, 2017.",
      "Yadav S., Anand N., Sahu S. K., Thermal performance in an annuli formed by smooth inner tube and outer corrugated tube for turbulent flow regime in the counter flow. Proceedings of 24th National and 2nd International ISHMT-ASTFE Heat and Mass Transfer Conference (IHMTC2017), BITS Hyderabad, Telangana, India, December 27-31, 2017.",
      "Kothari R., Das S., Sahu S. K., Kundalwal S. I., Approximate analytical model for solidification process in a rectangular phase change material storage with internal fins, Proceedings of 6 th International Conference on Advances in Energy Research(ICAER2017), IIT Bombay, Mumbai, India, December 12-14, 2017.",
      "Nirgude V. V., Modak M., Sharma A. K., Sahu S. K., Experimental Study on Structured Surfaces for Nuclear Pool Boiling Enhancement, Proceedings of the ASME 2017 25th International Conference on Nuclear Engineering (ICONE25), Shanghai, China, May 14-18, 2017.(Selected as Qualified Student Award Winner of the student paper competition)",
      "Yadav A. K., Sharma P., Sharma A. K., Modak M., Nirgude V. V., Sahu S. K., Heat Transfer Characteristics of Downward Facing Hot Horizontal Surfaces using Mist Jet Impingement, Proceedings of the ASME 2017 25th International Conference on Nuclear Engineering (ICONE25), Shanghai, China, May 14-18, 2017.",
      "Sahu S. K., Agrawal M. K., Rewetting of hot surfaces: Modeling and Experiments, Proceedings of the 6th International and 43rd National Conference on Fluid Mechanics and Fluid Power (FMFP2016), Allahabad, India, December 15-17, 2016. (Invited Thematic Talk Paper)",
      "Sharma A. K., Mishra S. K., Modak M., Yadav S., Jain A. K., Sahu S. K., Experimental Investigation of Rewetting During Quenching of Hot Surface by Round Jet Impingement Using Aqueous Surfactants, Proceedings of the 6th International and 43rd National Conference on Fluid Mechanics and Fluid Power (FMFP2016), Allahabad, India, December 15-17, 2016.",
      "Modak M., Sharma A. K., Sahu S. K., An comparative study on heat transfer characteristics of hot surface during impinging jet cooling using Al2O3-water and CuO-water nanofluids, Proceedings of the 6th International and 43rd National Conference on Fluid Mechanics and Fluid Power (FMFP2016), Allahabad, India, December 15-17, 2016.",
      "Kushwaha H. M., Raj P. B., Sahu S. K., Heat Transfer Analysis of Small Scale Gaseous Flows in Slip Flow Region, Proceedings of the 6th International and 43rd National Conference on Fluid Mechanics and Fluid Power (FMFP 2016), Allahabad, India, December 15-17, 2016.",
      "Raj P. B., Nirgude V. V., Junaid S., Sahu S. K., Theoretical Model to Predict the Bubble Departure Diameter In Nucleate Pool Boiling, Proceedings of the 6th International and 43rd National Conference on Fluid Mechanics and Fluid Power (FMFP2016), Allahabad, India, December 15-17.",
      "Yadav S., Sharma A. K., Sahu S. K., Experimental Investigation of Heat Transfer and Friction Factor Characteristics of Annuli Formed by Smooth Inner Tube and Corrugated Outer Tube in Turbulent Flow, Proceedings of the 6th International and 43rd National Conference on Fluid Mechanics and Fluid Power, (FMFP2016), Allahabad, India, December 15-17, 2016.",
      "Nirgude V. V., Modak M., Sahu S. K., Experimental Investigation of Pool Boiling Characteristics of Isopropyl Alcohol on Smooth Copper and Aluminum Surface, Proceedings of the 6th International and 43rd National Conference on Fluid Mechanics and Fluid Power (FMFP2016), Allahabad, India, December 15-17, 2016.",
      "Modak M., Nirgude V. V., Sharma A. K., Sahu S. K., Experimental study on heat transfer characteristics circular jet impingement boiling on the variety of structured copper surfaces in stagnation zone, Proceedings of the ASME 2016 24th International Conference on Nuclear Engineering (ICONE24), Charlotte, NC, USA, June 26-30, 2016.(Selected as Qualified Student Award Winner of the student paper competition)",
      "Sharma A. K., Modak M., Sahu S. K., Experimental investigation of rewetting during quenching of hot surface by round jet impingement using Al2O3–water nanofluids, Proceedings of the ASME 2016 24th International Conference on Nuclear Engineering (ICONE24), Charlotte, NC, USA, June 26-30, 2016.",
      "Chougule S. S, Modak M., Sahu S. K., Heat transfer characteristics of CuO-water nanofluids jet impingement on a hot surface, Proceedings of the ASME 2016 5th Micro/Nanoscale Heat and Mass Transfer International Conference (MNHMT-2016), Biopolis, Singapore, January 3-6, 2016.",
      "Modak M., Garg K., Srinivasan S., Sharma A. K., Sahu S.K., Analysis of stagnation region heat transfer of two dimensional impinging jets on solid surfaces, Proceedings of the 1st ISHMT-ASTFE and 23rd National Heat and Mass Transfer Conference (IHMTC2015), ISRO, Thiruvananthapuram, India, December 17-20, 2015.",
      "Modak M., Chougule S. S., Sharma A. K., Sahu S. K., Experimental investigation to study the effect of CNT nanofluids on heat transfer characteristics of hot surface, Proceedings of the 1st ISHMT-ASTFE and 23rd National Heat and Mass Transfer Conference (IHMTC2015), ISRO, Thiruvananthapuram, India, December 17-20, 2015.",
      "Modak M., Sharma A. K., Jain A. K., Ashok, Chougule S. S., Sahu S. K., Heat transfer characteristics of hot surface using different surfactant additives in circular impinging jets, Proceedings of the 1st ISHMT-ASTFE and 23rd National Heat and Mass Transfer Conference (IHMTC2015), ISRO, Thiruvananthapuram, India, December 17-20, 2015.",
      "Chougule S. S., Sahu S. K., Heat Transfer Enhancements of Low Volume Concentration CNT/water Nanofluid and Wire Coil Inserts in a Circular Tube, Proceedings of the 5th International Conference on Advance in Energy Research (ICAER2015), IIT Bombay, India, December 15-17, 2015.",
      "Chougule S. S., Sahu S. K., Application of Paraffin Based Nanocomposite in Heat PipeModule for ElectronicEquipment Cooling, 5th International Conference on Advance in Energy Research(ICAER2015), Proceedings of the 5th International Conference on Advance in Energy Research (ICAER2015), IIT Bombay, India, December 15-17, 2015.",
      "Kushwaha H. M., Sahu S. K., Analysis of slip flow heat transfer between asymmetrically heated parallel plates, Proceedings of the 13th International Conference on Fluid Dynamics and Thermodynamics (ICFDT2015), London, UK, January 19-20, 2015.",
      "Agrawal M. K., Modak M., Sahu S. K., Heat transfer characteristics of hot surface using high alcohol surfactant by impinging liquid jet, Proceedings of the 41st National Conference and 5th International conference on Fluid Mechanics and Fluid Power (FMFP2014), IIT Kanpur, India, 2014.",
      "Agrawal M. K., Modak M., Chandra S., Gupta P., Sahu S. K., An experimental investigation to analyze the heat transfer characteristics of hot surface by obliquely impinging liquid jet, Proceedings of the 41st National Conference and 5th International conference on Fluid Mechanics and Fluid Power (FMFP2014), IIT Kanpur, India, December 12-14, 2014.",
      "Kushwaha H. M., Sahu S. K., Analysis of heat transfer in the slip flow region between parallel plates, Proceedings of the 41st National Conference and 5th International conference on Fluid Mechanics and Fluid Power (FMFP2014), IIT Kanpur, India, December 12-14, 2014.",
      "Chougule S. S., Sahu S. K., An Integrated Effect of PCM and Nanofluid Charged Heat Pipe for Electronics Cooling, Proceedings of the ASME 2014 12th International Conference on Nanochannels, Microchannels, and Minichannels (ICNMM2014), Illinois, Chicago, USA, August 13-17, 2014.",
      "Agrawal M. K., Garg K., Singh A., Sahu S. K., An analysis of a three-region conduction controlled rewetting of hot surface by variational method, Proceedings of the ASME 2014 22nd International Conference on Nuclear Engineering (ICONE22), Prague, Czech Republic, July 7-11, 2014.",
      "Shewale, S. P., Chougule S. S., Sahu S.K., Pise A. T., A Review of Heat Pipe with Nanofluid for Electronic Cooling, Proceedings of the 4th International Conference on Advances in Engineering and Technology (ICAET2014), Nagapattiam, India, May 2-3, 2014.",
      "Shewale, S.P., Chougule S. S., Sahu S.K., Pise A.T., A Review on Applications of PCM for Electronic Cooling, Proceedings of the 4th International Conference on Advances in Engineering and Technology (ICAET2014), Nagapattiam, India, May 2-3, 2014.",
      "Chougule S. S., Sahu S. K., Performance of Wickless Heat Pipe Flat Plate Solar Collectors Having Different Filling Ratios, Proceedings of the 22nd National and 11th ISHMT-ASME Heat and Mass Transfer Conference (ISHMT-ASME), IIT Kharagpur, India, December 28-31, 2013.",
      "Chougule S. S., Sahu S. K., Comparison Of Augmented Thermal Performance Of CNT/Water And Al2O3/Water Nanofluids In Transition Flow Through A Straight Circular Duct Fitted With Helical Screw Tape Inserts, Proceedings of the 22nd National and 11th ISHMT-ASME Heat and Mass Transfer Conference (ISHMT-ASME), IIT Kharagpur, India, December 28-31, 2013.",
      "Chougule S. S., Sahu S. K., Comparative Study Of Cooling Performance Of Automobile Radiator Using Al2O3/Water And CNT/Water Nanofluid, Proceedings of the 22nd National and 11th ISHMT-ASME Heat and Mass Transfer Conference (ISHMT-ASME), IIT Kharagpur, India, December 28-31, 2013..",
      "Chougule S. S., Sahu S. K., Augmentation Of Convective Heat Transfer By Addition Of High-Alcohol Surfactant (HAS), Proceedings of the 22nd National and 11th ISHMT-ASME Heat and Mass Transfer Conference (ISHMT-ASME), IIT Kharagpur, India, December 28-31, 2013.",
      "Kushwaha H. M., Sahu S.K., Analysis of second order slip flow heat transfer in micro tube, Proceedings of the 22nd National and 11th ISHMT-ASME Heat and Mass Transfer Conference (ISHMT-ASME), IIT Kharagpur, India, December 28-31, 2013.",
      "Kushwaha H. M., Sahu S.K., Verma A., Analysis of slip flow heat transfer between parallel plates with constant heat flux boundary conditions, Proceedings of the 22nd National and 11th ISHMT-ASME Heat and Mass Transfer Conference (ISHMT-ASME), IIT Kharagpur, India, December 28-31, 2013.",
      "Agrawal M. K., Sahu S.K., Conduction controlled rewetting analysis of a hot surface by variational method, Proceedings of the 22nd National and 11th ISHMT-ASME Heat and Mass Transfer Conference (ISHMT-ASME), IIT Kharagpur, India, December 28-31, 2013.",
      "Patil N. D., Sahu S. K., Das P.K., Bhattacharyya, Rewetting of a single heater rod with and without counter current flow, Proceedings of the 22nd National and 11th ISHMT-ASME Heat and Mass Transfer Conference (ISHMT-ASME), IIT Kharagpur, India, December 28-31, 2013.",
      "Chougule S. S., Sahu S. K., Experimental Investigation of Heat Transfer Augmentation in automobile radiator with CNT’s/water nanofluid, Proceedings of the 4th ASME Micro/Nanoscale Heat & Mass Transfer International Conference (MNHMT2013), Hong Kong, China, December 11-14, 2013.",
      "Chougule S. S., Sahu S. K., Pise T. A., Performance enhancement of two phase thermosyphon solar water heater by using surfactant, Proceedings of the 17th International Heat Pipe Conference (IHPC2013), IIT Kanpur, Kanpur, India, October 13-17, 2013.",
      "Sahu S. K., Das P. K., Bhattacharyya S., Counter current flow limit for air and water in cold and heated condition, Proceedings of the International Conference on Multiphase flow (ICMF2013), Korea, May 26-31, 2013.",
      "Chougule S. S., Sahu S. K., Model of Heat Conduction in Hybrid Nanofluid, Proceedings of the International Conference on Emerging Trends in Computing, Communication and Nano Technology (ICECCN2013), India, March 25-26, 2013.",
      "Sahu S. K., Chandranan K., Assessment of Capability of Theoretical Correlations for Prediction of Pressure Drop of Fuel Pins with Grid Spacer, Proceedings of the 9th International Conference on Heat Transfer, Fluid Mechanics and Thermodynamics, Malta, (HEFAT2012), Malta, July 22-26, 2012.",
      "Sahu S. K., Das P. K., Bhattacharyya S., Rewetting analysis of hot tube with precursory cooling, Proceedigns of the 5th International Conference on Diffusion in Solids and Liquids (DSL2009), Rome, Italy, 24-26 June, 2009.",
      "Sahu S. K., Das P. K., Bhattacharyya S., Rewetting analysis of hot solids with internal heat source, Proceedings of the 8th ISHMT-ASME, Heat & Mass Transfer Conference (ISHMT-ASME, JNTU, Hyderabad, India, 2008.",
      "Sahu S. K., Das P. K., Bhattacharyya S., Rewetting analysis of hot surfaces by the Heat Balance Integral Method, Proceedings of the 3rd BSME-ASME International Conference on Thermal Engineering (BSME-ASME), Dhaka, Bangladesh, December 2006.",
      "Sahu S. K., Das P. K., Bhattacharyya S., Rewetting analysis of a thin vertical tube by the Heat Balance Integral Method, Proceedings of the International Conference on Computational Fluid Dynamics, Acoustics, Heat Transfer and Electromagnetics, Andhra University, Visakhapatnam, India, July 2006.",
      "Sahu S. K., Das P. K., Bhattacharyya S., Experimental Study to Investigate Quenching of a Vertical Thin Tube, Proceedings of the 18th National & 7th ISHMT-ASME Heat and Mass Transfer Conference (ISHMT-ASME), IIT Guwahati, India, January 2006."
    ],
    "National Conferences": [
      "Chandel S. S., Verma A., Paulraj M. P., Sahu S. K., Nusselt number and friction factor characteristics of circular wavy transverse rib artificially roughened solar air heater, Proceedings of National Conference on Recent Advances in Fuel Cells and Solar Energy (N-CRFS), May 11-12, 2019, NIT Puducherry, Puducherry, India.",
      "Chandra S., Gupta P., Agrawal M. K., Sahu S. K., Heat Transfer Characteristics of an Obliquely Impinging Liquid Jet, Proceedings of the 40th National Conference on Fluid Mechanics and Fluid Power, NIT Hamirpur, India, 2013.",
      "Sahu S. K., Agrawal M. K., Application of Various Measurement Techniques to Analyze Rewetting of Hot Surfaces, The Institution of Engineers (India), All India seminar on Computer application in Engineering: Emerging trends and technologies, India, November 22-23, 2013 (Invited expert lecture article)",
      "Sahu S. K., Sharma G. K., Modeling of steam jet pump, Proceedings of the 31st National Conference on Fluid Mechanics and Fluid Power (FMFP2004), Jadavpur University, India, 2004."
    ]
  }
};
